# Generated by Django 3.0.7 on 2020-06-13 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
