# Generated by Django 3.0.7 on 2020-06-13 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_auto_20200613_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drivers',
        ),
        migrations.AddField(
            model_name='car',
            name='first_owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
