# Generated by Django 3.0.7 on 2020-06-14 04:21

import cars.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_auto_20200613_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(limit_choices_to=cars.models.limit_car_choice, on_delete=models.SET(cars.models.set_delete_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
